In [2]:
import tensorflow as tf
import pandas as pd
from timeit import default_timer as timer
import os

In [14]:
start = timer()
dirname = os.getcwd()
dirname = os.path.dirname(dirname)
dataset_path = os.path.join(dirname, 'datasets/')
print(dataset_path)

gloveVectors =  pd.read_csv(dataset_path+'glove.42B.10d.txt', sep=' ', header=None )
print(gloveVectors.shape)

words = gloveVectors.iloc[:,0:1]
vectors = gloveVectors.iloc[:,1:]

end = timer()
print('Time taken to load word embeddings (seconds): ', end-start)

(1783088, 11)
Time taken to load word embeddings (seconds):  7.706441365997307


In [15]:
tf.enable_eager_execution()

In [16]:
embeddings = tf.get_variable(name='embeddings', shape = vectors.shape, initializer=tf.constant_initializer(vectors.values), dtype=tf.float32, trainable=False)
W = tf.get_variable(name='W', shape=(vectors.shape[1], 1), dtype=tf.float32)
b = tf.get_variable(name='W', shape=(1, 1), dtype=tf.float32)

In [17]:
y_predict = tf.matmul(embeddings, W) + b

In [18]:
y_predict

<tf.Tensor: id=124, shape=(1783088, 1), dtype=float32, numpy=
array([[ 1.794288 ],
       [ 2.1566005],
       [ 1.5723072],
       ...,
       [-1.1710095],
       [-1.2406161],
       [-1.0229455]], dtype=float32)>

In [19]:
embeddings

<tf.Variable 'embeddings:0' shape=(1783088, 10) dtype=float32, numpy=
array([[ 0.18378   , -0.12123   , -0.11987   , ...,  0.80795   ,
         0.067338  , -0.13184   ],
       [-0.20838   , -0.14932   , -0.017528  , ...,  0.62932   ,
         0.33672   , -0.43395   ],
       [ 0.10876   ,  0.0022438 ,  0.22213   , ..., -0.032631  ,
        -0.62594   , -0.51898   ],
       ...,
       [-0.052387  ,  0.32142   ,  0.23242   , ..., -0.58411   ,
        -0.091796  ,  0.51156   ],
       [-0.11969   ,  0.1602    , -0.24917   , ..., -0.1943    ,
         0.013091  ,  0.043389  ],
       [-0.00719714,  0.03803429,  0.06750505, ..., -0.25077328,
         0.07599969,  0.21972702]], dtype=float32)>

In [21]:
words = tf.nn.embedding_lookup(embeddings, [0, 1, 2])

<tf.Tensor: id=131, shape=(3, 10), dtype=float32, numpy=
array([[ 1.8378e-01, -1.2123e-01, -1.1987e-01,  1.5227e-02, -1.9121e-01,
        -6.6074e-02, -2.9876e+00,  8.0795e-01,  6.7338e-02, -1.3184e-01],
       [-2.0838e-01, -1.4932e-01, -1.7528e-02, -2.8432e-02, -6.0104e-02,
        -2.6460e-01, -4.1445e+00,  6.2932e-01,  3.3672e-01, -4.3395e-01],
       [ 1.0876e-01,  2.2438e-03,  2.2213e-01, -1.2102e-01, -4.8959e-02,
         1.8135e-02, -3.8174e+00, -3.2631e-02, -6.2594e-01, -5.1898e-01]],
      dtype=float32)>